### ISSUE TITLE
Trying to install/build on Ubuntu 14.04 LTS fails

### ISSUE THREAD

**Issue by nagyrobi** [vaibhavpandeyvpz/apkstudio#18]
Hello,

I'm trying to install/build on Ubuntu 14.04 LTS fails according to this:

mi@studio-mate:~/Programs/apkstudio$ make
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -o coder.o src/coder.cpp
src/coder.cpp: In constructor ‘ApkStudio::Coder::Coder(QWidget*)’:
src/coder.cpp:56:6: error: no matching function for call to ‘QTimer::singleShot(int, ApkStudio::Coder::Coder(QWidget*)::__lambda6)’
     });
      ^
src/coder.cpp:56:6: note: candidates are:
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from ./include/coder.h:8,
                 from src/coder.cpp:8:
/usr/include/qt5/QtCore/qtimer.h:81:17: note: static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: note:   candidate expects 3 arguments, 2 provided
/usr/include/qt5/QtCore/qtimer.h:82:17: note: static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: note:   candidate expects 4 arguments, 2 provided
make: *** [coder.o] Error 1

Thanks for any suggestions...

**Comment by vaibhavpandeyvpz** [comment]
It needs **Qt 5.4+**, refer #17
